// fetch( `https://www.alphavantage.co/query?function=SYMBOL_SEARCH&keywords=${searchStock}&apikey=${shares_api}` )
// .then(res => res.json())
// .then( data => setSearchStock(data))
// fetch( `https://www.alphavantage.co/query?function=TIME_SERIES_INTRADAY&symbol=${stockIntraDay}interval=5min&apikey=${shares_api}` )
// .then(res => res.json())
// .then( data => setStockIntraDay(data))